version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gymerp-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
      - PORT=3000

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gymerp-api
    restart: always
    ports:
      - "4000:4000"
    command: ["npx", "tsx", "src/server/index.ts"]
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
      - PORT=4000
